<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // Disable foreign key checks temporarily if needed, then insert
        DB::table('countries')->insert([
            ['id' => 1, 'name' => 'China', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'CN', 'code' => '+86',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 2, 'name' => 'India', 'currency_type' => 1,   'currency' => 'INR', 'prefix' => 'IN', 'code' => '+91',  'img' => '66ed95d7f1aeb_flg_9.jpg', 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 3, 'name' => 'United States', 'currency_type' => 1,   'currency' => 'USD', 'prefix' => 'US', 'code' => '+1',  'img' => null, 'inactive' => 0, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 4, 'name' => 'Indonesia', 'currency_type' => 1,   'currency' => 'IDR', 'prefix' => 'ID', 'code' => '+62',  'img' => '66ed95ee9e164_flg_1.jpg', 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 5, 'name' => 'Pakistan', 'currency_type' => 1,  'currency' => 'PKR', 'prefix' => 'PK', 'code' => '+92',  'img' => '66ed96205dbbb_flg_3.jpg', 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 6, 'name' => 'Brazil', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'BR', 'code' => '+55',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 7, 'name' => 'Nigeria', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'NG', 'code' => '+234',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 8, 'name' => 'Bangladesh', 'currency_type' => 2,   'currency' => 'TK', 'prefix' => 'BD', 'code' => '+880',  'img' => '66ed94d561629_flg_5.jpg', 'inactive' => 0, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 9, 'name' => 'Russia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'RU', 'code' => '+7',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 10, 'name' => 'Mexico', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MX', 'code' => '+52',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 11, 'name' => 'Japan', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'JP', 'code' => '+81',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 12, 'name' => 'Ethiopia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'ET', 'code' => '+251',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 13, 'name' => 'Philippines', 'currency_type' => 1,   'currency' => 'PHP', 'prefix' => 'PH', 'code' => '+63',  'img' => '66ed962b23378_flg_6.jpg', 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 14, 'name' => 'Egypt', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'EG', 'code' => '+20',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 15, 'name' => 'Vietnam', 'currency_type' => 1,   'currency' => 'VND', 'prefix' => 'VN', 'code' => '+84',  'img' => '66ed96396fd13_flg_4.jpg', 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 16, 'name' => 'DR Congo', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'CG', 'code' => '+242',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 17, 'name' => 'Turkey', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'TR', 'code' => '+90',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 18, 'name' => 'Iran', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 19, 'name' => 'Germany', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'DE', 'code' => '+49',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 20, 'name' => 'Thailand', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'TH', 'code' => '+66',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 21, 'name' => 'United Kingdom', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'GB', 'code' => '+44',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 22, 'name' => 'France', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'FR', 'code' => '+33',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 23, 'name' => 'Italy', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'IT', 'code' => '+39',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 24, 'name' => 'Tanzania', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 25, 'name' => 'South Africa', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'ZA', 'code' => '+27',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 26, 'name' => 'Myanmar', 'currency_type' => 1,   'currency' => 'MMK', 'prefix' => 'MM', 'code' => '+95',  'img' => '66ed9604c8edc_flg_2.jpg', 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 27, 'name' => 'Kenya', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'KE', 'code' => '+254',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 28, 'name' => 'South Korea', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 29, 'name' => 'Colombia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'CO', 'code' => '+57',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 30, 'name' => 'Spain', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'ES', 'code' => '+34',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 31, 'name' => 'Uganda', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'UG', 'code' => '+256',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 32, 'name' => 'Argentina', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'AR', 'code' => '+54',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 33, 'name' => 'Algeria', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'DZ', 'code' => '+213',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 34, 'name' => 'Sudan', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SD', 'code' => '+249',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 35, 'name' => 'Ukraine', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'UA', 'code' => '+380',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 36, 'name' => 'Iraq', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'IQ', 'code' => '+964',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 37, 'name' => 'Afghanistan', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'AF', 'code' => '+93',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 38, 'name' => 'Poland', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'PL', 'code' => '+48',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 39, 'name' => 'Canada', 'currency_type' => 1,   'currency' => 'CAD', 'prefix' => 'CA', 'code' => '+1',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 40, 'name' => 'Morocco', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MA', 'code' => '+212',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 41, 'name' => 'Saudi Arabia', 'currency_type' => 1,   'currency' => 'SR', 'prefix' => 'SA', 'code' => '+966',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 42, 'name' => 'Uzbekistan', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'UZ', 'code' => '+998',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 43, 'name' => 'Peru', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'PE', 'code' => '+51',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 44, 'name' => 'Angola', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'AO', 'code' => '+244',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 45, 'name' => 'Malaysia', 'currency_type' => 1,   'currency' => 'PTS', 'prefix' => 'MY', 'code' => '+60',   'img' => '66ed94eac6a9c_flg_8.jpg', 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 46, 'name' => 'Mozambique', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MZ', 'code' => '+258',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 47, 'name' => 'Ghana', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'GH', 'code' => '+233',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 48, 'name' => 'Yemen', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'YE', 'code' => '+967',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 49, 'name' => 'Nepal', 'currency_type' => 1,   'currency' => 'NPR', 'prefix' => 'NP', 'code' => '+977',   'img' => '66ed9611011e2_flg_7.jpg', 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 50, 'name' => 'Venezuela', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 51, 'name' => 'Madagascar', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MG', 'code' => '+261',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 52, 'name' => 'Cameroon', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'CM', 'code' => '+237',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 53, 'name' => 'Côte d\'Ivoire', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 54, 'name' => 'North Korea', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 55, 'name' => 'Australia', 'currency_type' => 1,   'currency' => 'AUD', 'prefix' => 'AU', 'code' => '+61',  'img' => null, 'inactive' => 0, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 56, 'name' => 'Niger', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 57, 'name' => 'Sri Lanka', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'LK', 'code' => '+94',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 58, 'name' => 'Burkina Faso', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'BF', 'code' => '+226',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 59, 'name' => 'Mali', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'ML', 'code' => '+223',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 60, 'name' => 'Romania', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'OM', 'code' => '+968',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 61, 'name' => 'Malawi', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MW', 'code' => '+265',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 62, 'name' => 'Chile', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'CL', 'code' => '+56',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 63, 'name' => 'Kazakhstan', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'KZ', 'code' => '+7',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 64, 'name' => 'Zambia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'ZM', 'code' => '+260',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 65, 'name' => 'Guatemala', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'GT', 'code' => '+502',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 66, 'name' => 'Ecuador', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'EC', 'code' => '+593',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 67, 'name' => 'Syria', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 68, 'name' => 'Netherlands', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'NL', 'code' => '+31',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 69, 'name' => 'Senegal', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SN', 'code' => '+221',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 70, 'name' => 'Cambodia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'KH', 'code' => '+855',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 71, 'name' => 'Chad', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'TD', 'code' => '+235',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 72, 'name' => 'Somalia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SO', 'code' => '+252',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 73, 'name' => 'Zimbabwe', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'ZW', 'code' => '+263',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 74, 'name' => 'Guinea', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'GN', 'code' => '+224',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 75, 'name' => 'Rwanda', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'RW', 'code' => '+250',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 76, 'name' => 'Benin', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'BJ', 'code' => '+229',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 77, 'name' => 'Burundi', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'BI', 'code' => '+257',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 78, 'name' => 'Tunisia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'TN', 'code' => '+216',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 79, 'name' => 'Bolivia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 80, 'name' => 'Belgium', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'BE', 'code' => '+32',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 81, 'name' => 'Haiti', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'HT', 'code' => '+509',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 82, 'name' => 'Cuba', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'CU', 'code' => '+53',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 83, 'name' => 'South Sudan', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SS', 'code' => '+211',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 84, 'name' => 'Dominican Republic', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'DO', 'code' => '+1849',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 85, 'name' => 'Czech Republic (Czechia)', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'CZ', 'code' => '+420',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 86, 'name' => 'Greece', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'GR', 'code' => '+30',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 87, 'name' => 'Jordan', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'JO', 'code' => '+962',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 88, 'name' => 'Portugal', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'PT', 'code' => '+351',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 89, 'name' => 'Azerbaijan', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'AZ', 'code' => '+994',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 90, 'name' => 'Sweden', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SE', 'code' => '+46',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 91, 'name' => 'Honduras', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'HN', 'code' => '+504',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 92, 'name' => 'United Arab Emirates', 'currency_type' => 1,   'currency' => 'AED', 'prefix' => 'AE', 'code' => '+971',  'img' => null, 'inactive' => 0, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 93, 'name' => 'Hungary', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'HU', 'code' => '+36',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 94, 'name' => 'Tajikistan', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'TJ', 'code' => '+992',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 95, 'name' => 'Belarus', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'BY', 'code' => '+375',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 96, 'name' => 'Austria', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'AT', 'code' => '+43',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 97, 'name' => 'Papua New Guinea', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'PG', 'code' => '+675',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 98, 'name' => 'Serbia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'RS', 'code' => '+381',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 99, 'name' => 'Israel', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'IL', 'code' => '+972',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 100, 'name' => 'Switzerland', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'CH', 'code' => '+41',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 101, 'name' => 'Togo', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'TG', 'code' => '+228',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 102, 'name' => 'Sierra Leone', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SL', 'code' => '+232',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 103, 'name' => 'Laos', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'LA', 'code' => '+856',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 104, 'name' => 'Paraguay', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'PY', 'code' => '+595',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 105, 'name' => 'Bulgaria', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'BG', 'code' => '+359',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 106, 'name' => 'Libya', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 107, 'name' => 'Lebanon', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'LB', 'code' => '+961',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 108, 'name' => 'Nicaragua', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'NI', 'code' => '+505',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 109, 'name' => 'Kyrgyzstan', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'KG', 'code' => '+996',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 110, 'name' => 'El Salvador', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SV', 'code' => '+503',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 111, 'name' => 'Turkmenistan', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'TM', 'code' => '+993',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 112, 'name' => 'Singapore', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SG', 'code' => '+65',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 113, 'name' => 'Denmark', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'DK', 'code' => '+45',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 114, 'name' => 'Finland', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'FI', 'code' => '+358',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 115, 'name' => 'Congo', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 116, 'name' => 'Slovakia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SK', 'code' => '+421',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 117, 'name' => 'Norway', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'NO', 'code' => '+47',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 118, 'name' => 'Oman', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 119, 'name' => 'State of Palestine', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 120, 'name' => 'Costa Rica', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'CR', 'code' => '+506',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 121, 'name' => 'Liberia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'LR', 'code' => '+231',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 122, 'name' => 'Ireland', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'IE', 'code' => '+353',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 123, 'name' => 'Central African Republic', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'CF', 'code' => '+236',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 124, 'name' => 'New Zealand', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'NZ', 'code' => '+64',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 125, 'name' => 'Mauritania', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MR', 'code' => '+222',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 126, 'name' => 'Panama', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'PA', 'code' => '+507',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 127, 'name' => 'Kuwait', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'KW', 'code' => '+965',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 128, 'name' => 'Croatia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'HR', 'code' => '+385',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 129, 'name' => 'Moldova', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MD', 'code' => '+373',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 130, 'name' => 'Georgia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'GE', 'code' => '+995',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 131, 'name' => 'Eritrea', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'ER', 'code' => '+291',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 132, 'name' => 'Uruguay', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'UY', 'code' => '+598',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 133, 'name' => 'Bosnia and Herzegovina', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'BA', 'code' => '+387',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 134, 'name' => 'Mongolia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MN', 'code' => '+976',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 135, 'name' => 'Armenia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'AM', 'code' => '+374',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 136, 'name' => 'Jamaica', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'JM', 'code' => '+1876',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 137, 'name' => 'Qatar', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'QA', 'code' => '+974',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 138, 'name' => 'Albania', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'AL', 'code' => '+355',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 139, 'name' => 'Lithuania', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'LT', 'code' => '+370',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 140, 'name' => 'Namibia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'NA', 'code' => '+264',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 141, 'name' => 'Gambia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'GM', 'code' => '+220',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 142, 'name' => 'Botswana', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'BW', 'code' => '+267',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 143, 'name' => 'Gabon', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'GA', 'code' => '+241',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 144, 'name' => 'Lesotho', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'LS', 'code' => '+266',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 145, 'name' => 'North Macedonia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MK', 'code' => '+389',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 146, 'name' => 'Slovenia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SI', 'code' => '+386',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 147, 'name' => 'Guinea-Bissau', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'GW', 'code' => '+245',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 148, 'name' => 'Latvia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'LV', 'code' => '+371',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 149, 'name' => 'Bahrain', 'currency_type' => 1,   'currency' => 'Rl', 'prefix' => 'BH', 'code' => '+973',  'img' => '675c34714a2d3_bh.png', 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 150, 'name' => 'Equatorial Guinea', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'GQ', 'code' => '+240',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 151, 'name' => 'Trinidad and Tobago', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'TT', 'code' => '+1868',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 152, 'name' => 'Estonia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'EE', 'code' => '+372',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 153, 'name' => 'Timor-Leste', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'TL', 'code' => '+670',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 154, 'name' => 'Mauritius', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MU', 'code' => '+230',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 155, 'name' => 'Cyprus', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'CY', 'code' => '+357',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 156, 'name' => 'Eswatini', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 157, 'name' => 'Djibouti', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'DJ', 'code' => '+253',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 158, 'name' => 'Fiji', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'FJ', 'code' => '+679',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 159, 'name' => 'Comoros', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'KM', 'code' => '+269',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 160, 'name' => 'Guyana', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'GY', 'code' => '+592',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 161, 'name' => 'Bhutan', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'BT', 'code' => '+975',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 162, 'name' => 'Solomon Islands', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SB', 'code' => '+677',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 163, 'name' => 'Montenegro', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'ME', 'code' => '+382',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 164, 'name' => 'Luxembourg', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'LU', 'code' => '+352',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 165, 'name' => 'Suriname', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SR', 'code' => '+597',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 166, 'name' => 'Cabo Verde', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 167, 'name' => 'Maldives', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MV', 'code' => '+960',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 168, 'name' => 'Malta', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MT', 'code' => '+356',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 169, 'name' => 'Brunei', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 170, 'name' => 'Belize', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'BZ', 'code' => '+501',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 171, 'name' => 'Bahamas', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'BS', 'code' => '+1242',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 172, 'name' => 'Iceland', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'IS', 'code' => '+354',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 173, 'name' => 'Vanuatu', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'VU', 'code' => '+678',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 174, 'name' => 'Barbados', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'BB', 'code' => '+1246',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 175, 'name' => 'Sao Tome & Principe', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 176, 'name' => 'Samoa', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'WS', 'code' => '+685',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 177, 'name' => 'Saint Lucia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'LC', 'code' => '+1758',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 178, 'name' => 'Kiribati', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'KI', 'code' => '+686',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 179, 'name' => 'Micronesia', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 180, 'name' => 'Grenada', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'GD', 'code' => '+1473',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 181, 'name' => 'St. Vincent & Grenadines', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 182, 'name' => 'Tonga', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'TO', 'code' => '+676',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 183, 'name' => 'Seychelles', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SC', 'code' => '+248',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 184, 'name' => 'Antigua and Barbuda', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'AG', 'code' => '+1268',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 185, 'name' => 'Andorra', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'AD', 'code' => '+376',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 186, 'name' => 'Dominica', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 187, 'name' => 'Marshall Islands', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MH', 'code' => '+692',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 188, 'name' => 'Saint Kitts & Nevis', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 189, 'name' => 'Monaco', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'MC', 'code' => '+377',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 190, 'name' => 'Liechtenstein', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'LI', 'code' => '+423',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 191, 'name' => 'San Marino', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'SM', 'code' => '+378',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 192, 'name' => 'Palau', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'PW', 'code' => '+680',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 193, 'name' => 'Tuvalu', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'TV', 'code' => '+688',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 194, 'name' => 'Nauru', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => 'NR', 'code' => '+674',  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['id' => 195, 'name' => 'Holy See', 'currency_type' => 1,   'currency' => 'TK', 'prefix' => null, 'code' => null,  'img' => null, 'inactive' => 1, 'created_at' => $now, 'updated_at' => $now],
        ]);
    }
}